apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-kafka-consumer
  template:
    metadata:
      labels:
        app: spring-boot-kafka-consumer
    spec:
      containers:
        - name: spring-boot-kafka-consumer
          image: rolandojavier13/spring-boot-kafka-consumer:v1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          resources:
            requests:
              memory: "512Mi"
              cpu: "256m"